### PR TITLE
Add RedisInsight v1.8 release notes

### PR DESCRIPTION
**Pull request by GnaneshKunal**
@slemeur

### CODE REVIEW

**Comment by GnaneshKunal** [comment]
**Do not merge without explicit approval.**

This PR should be merged along with https://github.com/RedisLabs/redislabs-docs/pull/1037.

**Review by slemeur — APPROVED** [review]

**Comment by slemeur** [comment]
LGTM

**Comment by GnaneshKunal** [comment]
@slemeur @bmansheim 

These PRs should also be merged along with the current one.

https://github.com/RedisLabs/redislabs-docs/pull/1106
https://github.com/RedisLabs/redislabs-docs/pull/1098
https://github.com/RedisLabs/redislabs-docs/pull/1037

**Comment by bmansheim** [comment]
> @slemeur @bmansheim
> 
> These PRs should also be merged along with the current one.
> 
> #1106
> #1098
> #1037

Done

**Pull request merged**
