### PR TITLE
RedisInsight: Added documentation on supported desktop OS.

### PR DESCRIPTION
**Pull request by nishantgeorge**
Screenshot from 2019-12-13 13-11-19

### CODE REVIEW

**Comment by bmansheim** [comment]
Waiting for update on download process

**Comment by nishantgeorge** [comment]
> Waiting for update on download process

Hey Ben, could you elaborate on this. What is the new download process and how does it affect supported OS's?

**Comment by bmansheim** [comment]
@nishantgeorge I had a problem that prevented me from downloading from the site. Please review that the process is correct for Ubuntu and MacOS.

**Comment by K-Jo** [comment]
@nishantgeorge @bmansheim let's hold back, I might create a google group instead of the mail address.

**Pull request merged**
