### PR TITLE
Update to upgrade procedure

### PR DESCRIPTION
**Pull request by amiramm**
Introduced pulling a version tag rather than cloning the repo.
TODO: add a user check for valid upgrade paths

### CODE REVIEW

**Comment by laurentdroin** [comment]
Do we not need to say anything about Openshift? In case (I don't know if it's likely) that something specific to the openshift bundle changes, we would want the customers to apply the openshift bundle, no?

Also, it might be the rendering in github causing this but I see some formatting issues:

Screen Shot 2021-02-22 at 7 06 20 AM

Screen Shot 2021-02-22 at 7 09 21 AM

**Comment by lanceleonard** [comment]
@laurentdroin - Use [this link](https://docs.redislabs.com/staging/amiramm-patch-1/platforms/kubernetes/tasks/upgrading-with-operator/) to view this doc on the staging server.  (Staging links only work until a PR is merged or closed.)

**Review by kaitlynmichael — APPROVED** [review]

**Comment by kaitlynmichael** [comment]
@laurentdroin @amiramm I reformatted the note, so now it renders correctly. Is this PR ready to merge?

**Comment by laurentdroin** [comment]
@amiramm I still have my initial concern - shouldn't we mention openshift?

**Comment by amiramm** [comment]
> @amiramm I still have my initial concern - shouldn't we mention openshift?

@laurentdroin can you please suggest some language for that?

**Comment by laurentdroin** [comment]
Reviewing all this, there are only two places that we need to amend for openshift and these are the actual commands we run to first download the bundle, and then apply the bundle.
So I guess that we should probably say something like "if you are using Openshift, run this instead:", twice. One time for each command.
We need to be careful not to make Openshift seems like a 2nd class citizen because it is actually more prevalent than non-OIpenshift, at least with all the customers I work with.

**Review by laurentdroin — CHANGES_REQUESTED** [review]
Updated the file but not sure if my change worked.

**Review by kaitlynmichael — APPROVED** [review]

**Review by kaitlynmichael — APPROVED** [review]

**Pull request merged**
