### PR TITLE
Add style for images that should not be clickable

### PR DESCRIPTION
**Pull request by HarunD**

### CODE REVIEW

**Comment by bmansheim** [comment]
@HarunD How do we apply this style to the icons?
You can use this page to see how they look: https://docs.redislabs.com/staging/icon-images/rv/administration/setup_and_editing/view-edit-subscription/

**Comment by HarunD** [comment]
@bmansheim sorry, I forgot to add it in the PR description.
To apply the style you need to define the icon like this:
`icon_add`

Note the **#no-click** at the end of the icon path. With this we can target specific links in CSS and style them.

**Comment by bmansheim** [comment]
@HarunD I tried but it didn't work for me. Try find *icon_(.*)png* and replace with *icon_$1png#no-click*.

**Comment by HarunD** [comment]
@bmansheim I will take a look at that. Thanks for letting me know.

**Pull request merged**
