### PR TITLE
RED-26382 Add instruction to specify database port number in docker

### PR DESCRIPTION
**Pull request by bmansheim**

### CODE REVIEW

**Comment by bmansheim** [comment]
@tylytran Is this change good?

**Comment by tylytran** [comment]
@bmansheim Sorry for the delayed response.  I was on vacation in the past 2 weeks.
Step 3:  "Click Show advanced options and, in the Endpoint port number, enter 12000 for the port number."
Should be done before "click Activate to create your database".  

It should be:
2. Enter a database name such as database1
3. Click **Show advanced options** and, in the Endpoint port number, enter 12000 (or any unused port number, between 10000 to 19999).
4. Click **Activate** to create your database

Then update the test connection section to:

Run redis-cli, located in the /opt/redislabs/bin directory, to connect to the database with the port number, specified in step 3 above, and to store and retrieve a key in database1.

**Comment by tylytran** [comment]
@bmansheim I forgot to mention, please remove the 'sudo' from the connection string in Step 5: .  

/opt/redislabs/bin/redis-cli -p 12000

sudo requires a password which the customer does not have.  The above comment works well without sudo.  Thanks

**Comment by bmansheim** [comment]
@tylytran Hope you had a good vacation! I implemented your changes a little differently to emphasize that 12000 should work and keep the Getting Started simple. OK?

**Comment by tylytran** [comment]
@bmansheim Changes look good.  Thanks!

**Pull request merged**
