### PR TITLE
Map port 9443 in Docker getting started

### PR DESCRIPTION
**Pull request by laurentdroin**
Need to also map port 9443.

### CODE REVIEW

**Comment by Paz-Yanover** [comment]
@ushachar - is it a must to add port 9443 while running RE on docker?

**Comment by ushachar** [comment]
Not an absolute must, but much more convenient.

**Comment by bmansheim** [comment]
@ushachar If this is the only other port that someone might want then I'll add it. If someone might want to add other ports also, I suggest that instead we write: "For other ports to open, see "Network Configuration". What do you think? (cc: @Paz-Yanover )

**Comment by bmansheim** [comment]
@ushachar @Paz-Yanover I'll add the port and a link to the list of ports in case customers want others.

**Pull request merged**
