### PR TITLE
DOC-737 K8s 6.0.20-4 release notes

### PR DESCRIPTION
**Pull request by kaitlynmichael**
DOC-737 K8s release notes for 6.0.20-4 
pulled from: https://github.com/RedisLabs/redis-enterprise-k8s-docs/releases/tag/v6.0.20-4

### CODE REVIEW

**Review by laurentdroin — COMMENTED** [review]
We're missing the following, is it on purpose?

Compatibility Notes
OpenShift 4.7 and Rancher/kOps 1.20 are now supported
OpenShift 4.1, 4.2, 4.3 (previously deprecated) are no longer supported
GKE K8s version 1.14 (previously deprecated) is no longer supported
kOps (upstream K8s) 1.13, 1.14 (previously deprecated) are no longer supported

Deprecation notice
OpenShift 4.4 (no longer supported by Red Hat) is deprecated
GKE K8s versions 1.15, 1.16 (no longer supported by Google) are deprecated
kOps (upstream K8s) 1.15 is deprecated

**Comment by laurentdroin** [comment]
Also, in order to stay consistent with the previous RN, don't we want to keep the title for each known limitation? The titles seem to have been stripped from the source github page.

**Comment by kaitlynmichael** [comment]
I understand that we want to be consistent but I didn't think the Jira numbers and titles were adding any value on the public site. Internally, they are useful. For the public , I believe just a description of the problem was all that's necessary. If this has a significant negative impact on customers, of course we can include the titles and numbers.

**Comment by kaitlynmichael** [comment]
> We're missing the following, is it on purpose?

Good catch! It is not on purpose. I'll add those asap.

**Comment by amiramm** [comment]
> understand that we want to be consistent but I didn't think the Jira numbers and titles were adding any value on the public site. Internally, they are useful. For the public, I believe just a description of the problem is all that's necessary. If this has a significant negative impact on customers, we can include the titles and numbers.

@kaitlynmichael we use these ticket numbers with customers and they expect to see them. Otherwise, every time we would need to refer to an issue, we would need to repeat the entire description and that's just not practical. We need to keep those, please. Thanks.

**Review by amiramm — CHANGES_REQUESTED** [review]
Thanks for this! please review comments/edits.

**Pull request merged**
