### PR TITLE
Configure AWS instance with only needed ports

### PR DESCRIPTION
**Pull request by OrenKarmi**
Ben, please check that the link indeed works before committing.
This resolves RED-28446
Thanks, Oren

### CODE REVIEW

**Comment by bmansheim** [comment]
@OrenKarmi Who can test it?

**Comment by bmansheim** [comment]
@OrenKarmi I'll check the link in staging.

**Comment by OrenKarmi** [comment]
Thank you Ben

Sent from Mail for Windows 10

**Comment by bmansheim** [comment]
@Paz-Yanover I merged this by mistake. Please approve that we want to instruct users to create AWS instances with specified ports opened.

**Pull request merged**
