### PR TITLE
RC: Active-Passive with TLS

### PR DESCRIPTION
**Pull request by cmilesb**
Ticket: DOC-3533
Staging links: 
https://docs.redis.com/staging/DOC-3533/rc/subscriptions/upgrade-fixed-flexible/
https://docs.redis.com/staging/DOC-3533/rc/databases/migrate-databases/

### CODE REVIEW

**Review by joniredis — APPROVED** [review]
Thanks for much @cmilesb for handling this so quickly.  Looks good to me. One thought: do we want to add to the changelog that "Active-Passive now supports source databases that require connections over TLS"?

**Comment by cmilesb** [comment]
@joniredis Just added changelog info in [b37f49b](https://github.com/RedisLabs/redislabs-docs/pull/3200/commits/b37f49bdbdb3ffb76fe4d088adda84abb3b273de)

**Comment by joniredis** [comment]
Awesome :) Thanks @cmilesb

**Review by mich-elle-luna — APPROVED** [review]
thank you!

**Pull request merged**
