### PR TITLE
Add instructions to use Terraform to give Redis Labs access to setup RC in customer account

### PR DESCRIPTION
**Pull request by TobyHFerguson**
Added a terraform module which automates all of this work, leveraging the newly released RedisCloud Terraform provider.

This work is incomplete, in the sense that the module needs to be moved from my personal Github account to a RedisLabs account, but is otherwise functional and tested. Who needs to move this module across and exactly where they must move it to is something we need to figure out. 

Furthermore, the module includes the two policy files - it would be good to automate the updating of this module when those two files are themselves updated.

### CODE REVIEW

**Comment by TobyHFerguson** [comment]
This is in draft form because:

1. There appears to be two bugs with Terraform which need to be investigated
2. The project needs to be moved to a RedisLabs owned git repo

**Comment by kaitlynmichaelredislabs** [comment]
@TobyHFerguson if this project isn't released yet, I think we should close this pull request and open a Jira ticket to track this work. Does that work for you?

**Comment by TobyHFerguson** [comment]
A fix for each of the two issues has now been pushed to the terraform module and we're waiting on figuring out how to get this module published to the Terraform registry. 

In the meantime moving this to a Jira ticket will be fine. Can you please make sure my manager, Colin Stevenson, is added to that Jira. He's the person who is figuring out the terraform registry logistics.

**Comment by kaitlynmichaelredislabs** [comment]
This work is now being tracked internally in DOC-569

**Pull request closed without merging**
