### PR TITLE
RED-35289 Unify RC Pro and Cloud docs

### PR DESCRIPTION
**Pull request by bmansheim**

### CODE REVIEW

**Comment by bmansheim** [comment]
@HarunD For this PR we need to add a URL replace rule that replaces all of these URL requests:

- /rc/ > /rcessentials/
- /rv/ > /rcpro/

That way we won't have to make aliases for all of these pages.

**Comment by bmansheim** [comment]
Here is the result:
image

**Comment by bmansheim** [comment]
@HarunD I don't see that the rewrite rule in the htaccess file is working either on the staging site or on local build. Maybe we can do the redirect in the head.html file like you did with the /embeds ?

**Comment by HarunD** [comment]
@bmansheim I will try that approach later today and let you know how it works.

**Pull request merged**
