### PR TITLE
Redis Enterprise Software Security

### PR DESCRIPTION
**Pull request by banker**

### CODE REVIEW

**Comment by bmansheim** [comment]
Hi @banker . I like the videos! I'll start reviewing and send you my comments.

**Comment by bmansheim** [comment]
@banker Ready for review: https://docs.redislabs.com/staging/DOC-315-RS-Security/rs/security/

**Comment by AlonMagrafta** [comment]
@bmansheim @banker (@amiramm fyi) where do we stand with this?

**Comment by banker** [comment]
@AlonMagrafta Working on a final review. Will get this out this week.

**Comment by bmansheim** [comment]
@banker I rebased the branch but there are broken links that need to be resolved (https://app.circleci.com/pipelines/github/RedisLabs/redislabs-docs/1540/workflows/728117a3-270e-46f4-ba59-e005eba17442/jobs/9154)

**Review by lanceleonard — APPROVED** [review]

**Pull request merged**
