### PR TITLE
Make shortcodes work in embedded files

### PR DESCRIPTION
**Pull request by HarunD**
This PR makes the shortcodes render properly when used within an embedded file, thanks to a [post on Hugo forum](https://discourse.gohugo.io/t/readfile-does-not-parse-shortcodes/16667/8?u=harun).

In order to work the embeds needed to be moved within the **content** directory.

[Cheatsheet](https://docs.redislabs.com/staging/shortcodes-embeds/cheatsheet/) has been updated to demonstrate an example of this (in the "Embed a markdown partial" section).

### CODE REVIEW

**Comment by HarunD** [comment]
@bmansheim `/embeds` page is not accessible via URL anymore and `/categories/platforms` page is disabled now.

**Comment by bmansheim** [comment]
@HarunD I just checked before merging and saw that the embed file itself is generated as an HTML file: https://docs.redislabs.com/staging/shortcodes-embeds/embeds/backup-locations/

**Comment by HarunD** [comment]
@bmansheim I see. I will check what can be done.

**Comment by HarunD** [comment]
@bmansheim Embeds are no longer accessible directly (via URLs). 
https://docs.redislabs.com/staging/shortcodes-embeds/embeds/backup-locations/ - the browser will be redirected to home page.

**Pull request merged**
