### PR TITLE
Add metrics exporter to updating-certificates.md

### PR DESCRIPTION
**Pull request by GitaShmueli**
Need to add info about metrics exporter certificate

### CODE REVIEW

**Comment by bmansheim** [comment]
According to @Paz-Yanover it's not necessary unless a customer raises an issue.

**Comment by Paz-Yanover** [comment]
@GitaShmueli - why did you raise this issue? is it a customer request?

**Comment by bmansheim** [comment]
@Paz-Yanover Per @GitaShmueli Not a customer request.

**Comment by Paz-Yanover** [comment]
@bmansheim - ok, thanks

**Pull request closed without merging**
