### PR TITLE
Update hamburger menu, footer and favicon

### PR DESCRIPTION
**Pull request by bmansheim**

### CODE REVIEW

**Comment by bmansheim** [comment]
To update the navigation menus:

1. Open a page in the redislabs.com website.
2. View the source of the page.
3. Copy the `<nav role="navigation">` section to another file.
4. Open the `layouts/partials/navigation.html` file in the docs site.
5. In the navigation.html file, replace the content of each `<div class="nav-column">` section with the contents of each <div class="column column-block"> section from the source of the redislabs.com page.
6. Review the links to make sure there are no unnecessary href tags.
7. Find any relative href tags, for example `href="/redis-enterprise/"` and add `https://redislabs.com` after the = symbol.
8. Commit the new navigation.html file to a new branch in the redislabs-docs GitHub repository.

**Comment by bmansheim** [comment]
To update the footer:

1. Open a page in the redislabs.com website.
2. View the source of the page.
3. Copy the <ul class="footer-action"> section to another file.
4. Open the layouts/partials/footer.html file in the docs site.
5. In the footer.html file, replace the contents of each <ul class="footer-action"> section with the contents that section from the source of the redislabs.com page.
7. Review the social links to make sure there are no unnecessary css tags.
8. Commit the new footer.html file to a new branch in the redislabs-docs GitHub repository.

**Comment by bmansheim** [comment]
@HarunD I needed to update the navigation and footer to match the redislabs.com website. On my machine I saw some strange behaviors like the menu arrows won't open and screenshots aren't clickable. Please look at the staging site https://docs.redislabs.com/staging/update-hamburger-menu/rs/getting-started/quick-setup/ and confirm that it all looks OK.
Thanks!

**Comment by bmansheim** [comment]
To update the favicon:

1. Go to: https://github.com/RedisLabs/redislabs-docs/tree/master/static/images/icon_logo
2. Click Upload files.
3. Drag-and-drop the file or browse to the new favicon file and click Open.
4. In the "Create a new branch" field, enter a name for the branch, for example: change-favicon
5. Click Propose changes.
6. Open a pull request with the change.

If you upload a file that is not named the same as the old favicon:
1. Go to: https://github.com/RedisLabs/redislabs-docs/edit/<branch-name>/layouts/partials/flex/head.html
2. Find the old favicon filename and change it to the new name.
3. Commit the change.

**Comment by HarunD** [comment]
@bmansheim menu icons work (they open the menus) and screenshots are clickable, so everything looks fine to me

**Pull request merged**
