### PR TITLE
Migrate rdbtools docs

### PR DESCRIPTION
**Pull request by bmansheim**

### CODE REVIEW

**Comment by bmansheim** [comment]
- Migrate images
- Change product name to RedisInsight
- Add RI category to articles so that they show properly in search
- Order articles in the TOC
- Add RedisInsight to list of products at the bottom of the TOC
- Fix internal links in the articles
- Get icon for RedisInsight from Yifat
- Add RedisInsight to docs landing page
- Make sure the content is formatted correctly (bullets, indentation)
- Migrate the FAQs
- flow & structure
- rebranding of product names
- copyrights, addresses and other company info

**Comment by bmansheim** [comment]
@HarunD The pages in the new ri section have variables for some values in the format of `{{ site.<variable> }}. I need to change the syntax to meet Hugos requirements and add these variables as site parameters to the config.toml:

mac_dl_link: "https://binaries.rdbtools.com/v0.9.40.1/rdbtools-mac-v0.9.40.1.dmg"
linux_dl_link: "https://binaries.rdbtools.com/v0.9.40.1/rdbtools-linux64-v0.9.40.1"
windows_dl_link: "https://binaries.rdbtools.com/v0.9.40.1/rdbtools-win-v0.9.40.1.msi"
docker_command: "docker run -v rdbtools:/db -p 8001:8001 rdbtools/rdbtools"
docker_image_version: "v0.9.40.1"
aws_template_url: "https://console.aws.amazon.com/cloudformation/home?#/stacks/create/review?templateURL=https://s3.amazonaws.com/cf-templates-15mti4h67cldi-us-east-1/cf-docker-compose-no-IAM-rdbtools-version-all-parameter-required&param_RdbtoolsVersion= "

**Comment by HarunD** [comment]
@bmansheim I added those variables to config.toml and updated their usage. As you can see the way to use them in content files is like this:
`{{< param mac_dl_link >}}`

The only thing remaining is to see how to make the `replace` pipe work in markdown.

**Comment by bmansheim** [comment]
@HarunD The build failed because it couldn't find the shortcode.

**Comment by bmansheim** [comment]
@HarunD If you go to https://docs.redislabs.com/staging/migrate-rdbtools-docs/ you see that the RedisInsight box is higher than the other two. Please update the css so that it is even with the others.

**Comment by bmansheim** [comment]
@HarunD We need to add the top content in the TOC section to the RedisInsight pages.

image

**Comment by bmansheim** [comment]
@HarunD The replace function on the windows, mac and linux pages only replace one of the "version" placeholders and not both. Can you fix it?

image

**Pull request merged**
