### PR TITLE
create CRDB | Participant URL HTTPS port change

### PR DESCRIPTION
**Pull request by nail-sirazitdinov**
-- https://<cluster_URL>:8080
8080 is HTTP CNM port. Should be 9443 for SSL

### CODE REVIEW

**Comment by Paz-Yanover** [comment]
It can be 8080 or 9443 for the REST API.

**Comment by nail-sirazitdinov** [comment]
Right, http=>8080 or https=>9443
But not HTTPS 8080. Please correct me if I'm wrong.

**Comment by Paz-Yanover** [comment]
Correct. Let's use 8080 and http

**Comment by bmansheim** [comment]
@nail-sirazitdinov Please update the PR accordingly.

**Comment by nail-sirazitdinov** [comment]
@bmansheim, done

**Pull request merged**
