### PR TITLE
Fix line re: quorum loss check on maintenance mode

### PR DESCRIPTION
**Pull request by Paz-Yanover**
Let's discuss this change... We will probably need to add a warning or such

### CODE REVIEW

**Comment by Paz-Yanover** [comment]
@bmansheim - to clarify- the sentence is right but misleading.

**Comment by bmansheim** [comment]
Related to https://redislabs.atlassian.net/browse/RED-28852

**Comment by bmansheim** [comment]
@Paz-Yanover Please approve.

**Comment by bmansheim** [comment]
@RoeyPrat Once we agree on the warning text you can also use it in the CLI.

**Comment by RoeyPrat** [comment]
@bmansheim please update in ticket RED-29368 once you have the warning text, and assign to cluster team.
thanks!

**Comment by bmansheim** [comment]
@RoeyPrat Do you have any objections to the warning? If not then it's final.

**Comment by RoeyPrat** [comment]
> @RoeyPrat Do you have any objections to the warning? If not then it's final.

@bmansheim @Paz-Yanover  i would replace `simultaneously restart them` with `restart them simultaneously`. It makes more sense in the sentence.

**Comment by RoeyPrat** [comment]
@Ann

**Pull request merged**
