### PR TITLE
Issue-889 Reorg Redis optimizations in RI

### PR DESCRIPTION
**Pull request by bmansheim**
@slemeur Is there a way to put these in categories?

avoid-dynamic-lua-script.md
combine-smaller-strings-to-hash.md
compress-field-names.md
compress-values.md
convert-hash-to-ziplist.md
convert-to-list-instead-of-hash.md
enable-compression-for-list.md
reclaim-expired-keys-memory-faster.md
shard-big-hash-to-small-hash.md
switch-set-to-intset.md
switch-to-32-bits.md
switch-to-bloom-filters.md
upgrade-redis-version.md
use-better-serializer.md
use-smaller-keys.md

### CODE REVIEW

**Comment by slemeur** [comment]
I'm thinking about these: 

**Optimal use of Redis**
avoid-dynamic-lua-script.md
switch-to-32-bits.md
reclaim-expired-keys-memory-faster.md
use-better-serializer.md
upgrade-redis-version.md

**Data modeling recommendations**
combine-smaller-strings-to-hash.md
convert-hash-to-ziplist.md
switch-set-to-intset.md
use-smaller-keys.md
convert-to-list-instead-of-hash.md
shard-big-hash-to-small-hash.md
switch-to-bloom-filters.md

**Data compression**
compress-field-names.md
compress-values.md
enable-compression-for-list.md


WDYT ?

**Comment by bmansheim** [comment]
Sounds good to me.
@banker Let me know if you also have ideas.

**Comment by banker** [comment]
LGTM!

**Comment by bmansheim** [comment]
@slemeur I'll merge it. If you have more ideas let me know.

**Pull request merged**
