### PR TITLE
Update nagios-plugin.md

### PR DESCRIPTION
**Pull request by orenlandau**
The Nagios Plugin supports on Keyring and Base64 password stores.
The rest are not supported.

### CODE REVIEW

**Comment by bmansheim** [comment]
@paz@redislabs.com

**Comment by Paz-Yanover** [comment]
@ushachar - can you please review the PR? Do you know if we QA / maintain the plugin?
@bmansheim

**Comment by Paz-Yanover** [comment]
@ushachar - where is the source code of the plugin located? Can we share it in our website?
@orenlandau - can you share your updated version of the plugin?

**Comment by ushachar** [comment]
@Paz-Yanover - We do not maintain the nagios plugin - The code is under https://github.com/redislabsdev/management/tree/master/rlec_nagios

See:
https://redislabs.atlassian.net/browse/RED-12993
https://redislabs.atlassian.net/browse/RED-17505

**Comment by bmansheim** [comment]
@Paz-Yanover What's next with this one?

**Comment by Paz-Yanover** [comment]
@bmansheim - we don't have a decision yet who should support it (- SAs or 3rd party contractor)

**Comment by bmansheim** [comment]
@Paz-Yanover Ping

**Comment by Paz-Yanover** [comment]
@bmansheim - this issue is pending Alvin and Yiftach's decision

**Pull request closed without merging**
