### PR TITLE
Embed Shortcode

### PR DESCRIPTION
**Pull request by HarunD**
This PR moves RBAC table from Account Management to a partial file and import it back via **readFile** shortcode.

### CODE REVIEW

**Comment by bmansheim** [comment]
@HarunD That's really good to know. I forgot to mention that the table is the HTML table in the RED-24044-update-db-viewer branch. How would you do the same with the HTML table?
Also would a shortcode make it a simpler syntax? For example {{% embed-md "rs/partials/rbac-table.md" %}}

**Comment by HarunD** [comment]
@bmansheim I will add the same for HTML table you mentioned, and will also create two shortcodes for simpler syntax (one for md and one for HTML content).

**Comment by HarunD** [comment]
@bmansheim I added shortcodes for md and HTML, with simple usage syntax. They are used like this:
```
{{< embed-md "rs/partials/rbac-table.md" >}}
{{< embed-html "rs/partials/sample-table.html" >}}
```

[Here](https://docs.redislabs.com/staging/embed-shortcode/rs/administering/security/account-management/) you can see how this table looks.

If this looks good I will remove the testing file **sample-table.html** and its reference in **account-management.md.**

**Comment by bmansheim** [comment]
@HarunD Looks great. One comment: the relref and images syntax both include the leading / so maybe it would be good to keep that syntax consistent, if possible.

**Comment by bmansheim** [comment]
@HarunD I knew I shouldn't have said "one comment". 😄 
Probably best to keep these partials outside of the /content path so:

1. they don't get published into the site
2. so they are not associated with specific products (rs, rc, rv, etc)

**Comment by HarunD** [comment]
@bmansheim I've added the forward slash so the syntax is now consistent and have also moved the partials out of the `content` folder.
The `sample-table.html` is still there for testing, so once everything looks good to you let me know and I will delete that file.

**Comment by bmansheim** [comment]
@HarunD I think you can remove the sample-table.

**Comment by HarunD** [comment]
@bmansheim sample-table removed

**Pull request merged**
