### PR TITLE
Refreshes the node_redis client page.

### PR DESCRIPTION
**Pull request by simonprickett**
This pull request updates the `node_redis` client page for Node.js with the following additions and improvements:

* Generally overhauls the code to modern JavaScript, fixes previous syntax errors
* Adds section for using promises and async/await
* Adds section for connecting to Redis with an ACL user
* General tidy up of the prose

I propose to keep this page as is and open another pull request to add a second page as a sibling for it to cover the `ioredis` client... then have the first paragraph of this page reference `ioredis` as an alternative and the `ioredis` page reference this one as an alternative too... saves having a generic Node.js landing page I think?

### CODE REVIEW

**Comment by simonprickett** [comment]
Is anything required here @banker @bmansheim ? Thanks.

**Comment by bmansheim** [comment]
@simonprickett Sorry for the delay. I want to get @K-Jo 's opinion on it before we merge.

**Comment by bmansheim** [comment]
@K-Jo passed me to @gkorland

**Review by gkorland — APPROVED** [review]

**Comment by bmansheim** [comment]
@simonprickett Guy approved and I added my style changes. Any objections?

**Comment by simonprickett** [comment]
> @simonprickett Guy approved and I added my style changes. Any objections?

@bmansheim looks good to me, thanks!

**Pull request merged**
