### PR TITLE
DOC-405 Revamp getting started and installation

### PR DESCRIPTION
**Pull request by bmansheim**
This PR is to address a request from the field to have unified instructions that cover all steps up to creating a database.

Planning your RS deployment
Downloading the installation package
Installing RS on Linux
Set up the new cluster
Add more nodes to the cluster
Next steps

https://docs.redislabs.com/staging/revamp-getting-started/rs/installing-upgrading/

### CODE REVIEW

**Comment by AlonMagrafta** [comment]
@orshwartzredislabs I'll love your input here too.
See Ben's link to staging , might help with having a full overview and compare to the prev page.

**Comment by bmansheim** [comment]
@AlonMagrafta @orshwartzredislabs I'm in the process of making more changes based on feedback from SAs. Most helpful would be your thoughts on what information should not be included in this installation page, if any.

**Comment by AlonMagrafta** [comment]
@bmansheim ack

**Review by lanceleonard — APPROVED** [review]
Approving so we can get these live.  

Additional changes to be handled separately.

**Pull request merged**
