### PR TITLE
Support offline install steps - updated

### PR DESCRIPTION
**Pull request by shahar-biron**
According to the latest 6.2 offline install options.
@MeirShpilraien please review

### CODE REVIEW

**Review by MeirShpilraien — COMMENTED** [review]
This is not a correct fix, the instruction for Redis 6.0.12 and above are on the link specified and it also contains a note what to do on offline environment.

**Comment by K-Jo** [comment]
Let's not close this until @MeirShpilraien approved please.

**Comment by MeirShpilraien** [comment]
@K-Jo as I commented above, this change is wrong and misleading. Offline installation on 6.0.12 and above are describe here: https://docs.redis.com/latest/modules/add-module-to-cluster/. If something is not clear we should update this page.

**Comment by lanceleonard** [comment]
Closing this PR in favor of further review.

**Pull request closed without merging**
