### PR TITLE
Move Redis on Flash procedure later in docs

### PR DESCRIPTION
**Pull request by JeffreyGroves**
Problem with documentation:
The file /opt/redislabs/sbin/prepare_flash.sh is only extracted as part of the ./install.sh execution, so it is impossible to run it prior to step 4 *Answer the installation questions*

Solution: 
The Redis on Flash part should be moved from the *Prepare to install on Linux* section to the *Install on Linux* section, after step 4 *Answer the installation questions...* and before step 5. *Create or join an existing...*

Please let me know if you have any questions or concerns.
Kind regards,

Jeff Groves

### CODE REVIEW

**Comment by lanceleonard** [comment]
Hi @JeffreyGroves!  Thanks for the contribution.  

I see where you're going with this.  I'm not sure that moving the entire section is the right answer, but I will work our PM team to figure out the right way to present this info.

**Review by rrelledge — APPROVED** [review]
Looks good to me.

**Comment by nermiller** [comment]
@JeffreyGroves please sign the CLA. Thank you!

**Comment by JeffreyGroves** [comment]
Sorry for the delay in signing the CLA. I have just completed it.

**Comment by rrelledge** [comment]
Closing this PR without merging since #2965 fixes this.

**Pull request closed without merging**
