### PR TITLE
Note on eviction policy

### PR DESCRIPTION
**Pull request by ruslan-redislabs**
Eviction policy set to "noeviction" with modules enabled. Added a "Note:" on line 39.

### CODE REVIEW

**Comment by maguec** [comment]
:+1:

**Comment by K-Jo** [comment]
I don't believe this is a correct modification to our docs.  Each module declares it's enterprise capabilities.  We should find a way to explain those in our documenation
https://github.com/RedisLabs/RAMP#module-capabilities

**Comment by ruslan-redislabs** [comment]
Maybe a matrix per module/capability and a reference to it? Or in general, "If using modules, consider checking modules capability to see if eviction policies are supported"?

**Comment by bmansheim** [comment]
Resolved in https://github.com/RedisLabs/redislabs-docs/pull/521/commits/bc757936699a650cc002797f9b6b2333eb39c15a

**Pull request closed without merging**
