### PR TITLE
Add CLI option

### PR DESCRIPTION
**Pull request by andresrinivasan**
Copied from https://docs.redislabs.com/latest/rs/administering/troubleshooting/creating-support-package/. Not sure if there is an option to consolidate these two pages.

### CODE REVIEW

**Comment by banker** [comment]
@andresrinivasan You're asking to merge into the 5.2-build branch. Is this change only relevant to 5.2?

**Comment by andresrinivasan** [comment]
Should be latest. I accepted whatever was defaulted when I hit edit.

**Comment by bmansheim** [comment]
Replaced by https://github.com/RedisLabs/redislabs-docs/pull/1198

**Comment by bmansheim** [comment]
Hi @andresrinivasan . Looks like I moved too fast. Was your intention to add the CLI procedure to the 5.2 docs, or did you not notice that you were looking at the 5.2 docs?

In other words, the latest branch already has this content. Do you still feel that there needs to be a change?

**Comment by andresrinivasan** [comment]
I did not intend to update the 5.2 docs and I don't suggest making the change. Note these were the docs that were at the top of search results when I was trying to figure out how to create a support package from the command line.

**Pull request closed without merging**
